-- Add AI metadata and enhancement columns to todos table
ALTER TABLE todos ADD COLUMN IF NOT EXISTS ai_enhanced BOOLEAN DEFAULT FALSE;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS ai_generated_description BOOLEAN DEFAULT FALSE;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS task_emoji VARCHAR(10);
ALTER TABLE todos ADD COLUMN IF NOT EXISTS ai_category VARCHAR(50);
ALTER TABLE todos ADD COLUMN IF NOT EXISTS ai_priority VARCHAR(20);
ALTER TABLE todos ADD COLUMN IF NOT EXISTS ai_estimated_duration INTEGER; -- in minutes
ALTER TABLE todos ADD COLUMN IF NOT EXISTS ai_enhancement_version INTEGER DEFAULT 1;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS ai_metadata JSONB; -- Store additional AI data

-- Add AI flags to subtasks table
ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE;
ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS ai_estimated_duration INTEGER; -- in minutes
ALTER TABLE subtasks ADD COLUMN IF NOT EXISTS ai_metadata JSONB;

-- Create AI interaction log table
CREATE TABLE IF NOT EXISTS ai_interactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    todo_id UUID REFERENCES todos(id) ON DELETE CASCADE,
    interaction_type VARCHAR(50) NOT NULL, -- 'task_enhancement', 'subtask_refinement', 'description_improvement'
    request_data JSONB NOT NULL,
    response_data JSONB,
    tokens_used INTEGER,
    duration_ms INTEGER,
    success BOOLEAN DEFAULT TRUE,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_ai_interactions_user_id (user_id),
    INDEX idx_ai_interactions_todo_id (todo_id),
    INDEX idx_ai_interactions_type (interaction_type),
    INDEX idx_ai_interactions_created_at (created_at)
);

-- Create AI suggestions table for tracking AI-generated content
CREATE TABLE IF NOT EXISTS ai_suggestions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    todo_id UUID REFERENCES todos(id) ON DELETE CASCADE,
    subtask_id UUID REFERENCES subtasks(id) ON DELETE CASCADE,
    suggestion_type VARCHAR(50) NOT NULL, -- 'description', 'subtask', 'category', 'priority', 'emoji'
    original_content TEXT,
    suggested_content TEXT NOT NULL,
    ai_confidence DECIMAL(3,2), -- 0.00 to 1.00
    user_action VARCHAR(20), -- 'accepted', 'rejected', 'modified', 'pending'
    user_feedback TEXT,
    regeneration_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_ai_suggestions_user_id (user_id),
    INDEX idx_ai_suggestions_todo_id (todo_id),
    INDEX idx_ai_suggestions_type (suggestion_type),
    INDEX idx_ai_suggestions_action (user_action)
);

-- Add trigger to update updated_at on ai_suggestions
CREATE OR REPLACE FUNCTION update_ai_suggestions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ai_suggestions_update_trigger ON ai_suggestions;
CREATE TRIGGER ai_suggestions_update_trigger
    BEFORE UPDATE ON ai_suggestions
    FOR EACH ROW
    EXECUTE FUNCTION update_ai_suggestions_updated_at();

-- Add comments for documentation
COMMENT ON COLUMN todos.ai_enhanced IS 'Whether this task has been enhanced by AI';
COMMENT ON COLUMN todos.ai_generated_description IS 'Whether the description was generated by AI';
COMMENT ON COLUMN todos.task_emoji IS 'Emoji representation of the task (AI-suggested or user-selected)';
COMMENT ON COLUMN todos.ai_category IS 'AI-suggested category (Work, Personal, Bug, Feature, etc.)';
COMMENT ON COLUMN todos.ai_priority IS 'AI-suggested priority level (Low, Medium, High)';
COMMENT ON COLUMN todos.ai_estimated_duration IS 'AI-estimated duration in minutes';
COMMENT ON COLUMN todos.ai_enhancement_version IS 'Version number of AI enhancement (increments on regeneration)';
COMMENT ON COLUMN todos.ai_metadata IS 'Additional AI-related metadata as JSON';

COMMENT ON COLUMN subtasks.ai_generated IS 'Whether this subtask was generated by AI';
COMMENT ON COLUMN subtasks.ai_estimated_duration IS 'AI-estimated duration for this subtask in minutes';
COMMENT ON COLUMN subtasks.ai_metadata IS 'AI-related metadata for this subtask';

COMMENT ON TABLE ai_interactions IS 'Log of all AI API interactions for analytics and debugging';
COMMENT ON TABLE ai_suggestions IS 'Tracks AI suggestions and user actions for learning and improvement';
