package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

// TaskEnhancementRequest represents the request for AI task enhancement
type TaskEnhancementRequest struct {
	TaskName        string `json:"task_name"`
	TaskDescription string `json:"task_description,omitempty"`
	ProjectContext  string `json:"project_context,omitempty"`
	UserPreferences string `json:"user_preferences,omitempty"`
}

// TaskEnhancementResponse represents the AI response for task enhancement
type TaskEnhancementResponse struct {
	EnhancedDescription string               `json:"enhanced_description"`
	Emoji               string               `json:"emoji"`
	Subtasks            []AIGeneratedSubtask `json:"subtasks"`
	Category            string               `json:"category"`
	Priority            string               `json:"priority"`
	EstimatedDuration   int                  `json:"estimated_duration_minutes"`
	Tags                []string             `json:"tags"`
}

// AIGeneratedSubtask represents a subtask generated by AI
type AIGeneratedSubtask struct {
	Name              string `json:"name"`
	Description       string `json:"description"`
	EstimatedDuration int    `json:"estimated_duration_minutes"`
	Order             int    `json:"order"`
}

// AIClient defines the interface for AI clients
type AIClient interface {
	EnhanceTask(ctx context.Context, req TaskEnhancementRequest) (*TaskEnhancementResponse, error)
	RefineSubtasks(ctx context.Context, taskName string, existingSubtasks []string, userFeedback string) ([]AIGeneratedSubtask, error)
	ImproveDescription(ctx context.Context, taskName string, currentDescription string, priority string, tags []string) (string, error)
}

// GeminiClient handles AI requests to Google Gemini API
type GeminiClient struct {
	apiKey     string
	baseURL    string
	model      string
	httpClient *http.Client
	maxRetries int
	retryDelay time.Duration
}

// NewGeminiClient creates a new Google Gemini AI client with professional defaults
func NewGeminiClient(apiKey string) *GeminiClient {
	return &GeminiClient{
		apiKey:     apiKey,
		baseURL:    "https://generativelanguage.googleapis.com/v1beta",
		model:      "gemini-1.5-flash",
		maxRetries: 3,
		retryDelay: 2 * time.Second,
		httpClient: &http.Client{
			Timeout: 60 * time.Second, // Gemini can take longer for comprehensive responses
		},
	}
}

// NewGeminiClientWithConfig creates a new Google Gemini AI client with custom configuration
func NewGeminiClientWithConfig(apiKey, model string, timeout time.Duration, maxRetries int) *GeminiClient {
	return &GeminiClient{
		apiKey:     apiKey,
		baseURL:    "https://generativelanguage.googleapis.com/v1beta",
		model:      model,
		maxRetries: maxRetries,
		retryDelay: 2 * time.Second,
		httpClient: &http.Client{
			Timeout: timeout,
		},
	}
}

// GeminiRequest represents the API request structure for Gemini
type GeminiRequest struct {
	Contents         []GeminiContent        `json:"contents"`
	GenerationConfig GeminiGenerationConfig `json:"generationConfig"`
	SafetySettings   []GeminiSafetySettings `json:"safetySettings,omitempty"`
}

// GeminiContent represents the content structure
type GeminiContent struct {
	Parts []GeminiPart `json:"parts"`
	Role  string       `json:"role,omitempty"`
}

// GeminiPart represents a part of the content
type GeminiPart struct {
	Text string `json:"text"`
}

// GeminiGenerationConfig represents the generation configuration
type GeminiGenerationConfig struct {
	Temperature     float64  `json:"temperature"`
	TopK            int      `json:"topK"`
	TopP            float64  `json:"topP"`
	MaxOutputTokens int      `json:"maxOutputTokens"`
	StopSequences   []string `json:"stopSequences,omitempty"`
}

// GeminiSafetySettings represents safety settings
type GeminiSafetySettings struct {
	Category  string `json:"category"`
	Threshold string `json:"threshold"`
}

// GeminiResponse represents the API response structure
type GeminiResponse struct {
	Candidates    []GeminiCandidate   `json:"candidates"`
	UsageMetadata GeminiUsageMetadata `json:"usageMetadata"`
}

// GeminiCandidate represents a response candidate
type GeminiCandidate struct {
	Content       GeminiContent        `json:"content"`
	FinishReason  string               `json:"finishReason"`
	Index         int                  `json:"index"`
	SafetyRatings []GeminiSafetyRating `json:"safetyRatings"`
}

// GeminiSafetyRating represents safety rating
type GeminiSafetyRating struct {
	Category    string `json:"category"`
	Probability string `json:"probability"`
}

// GeminiUsageMetadata represents usage metadata
type GeminiUsageMetadata struct {
	PromptTokenCount     int `json:"promptTokenCount"`
	CandidatesTokenCount int `json:"candidatesTokenCount"`
	TotalTokenCount      int `json:"totalTokenCount"`
}

// EnhanceTask uses Google Gemini AI to enhance a task with description, subtasks, and metadata
func (c *GeminiClient) EnhanceTask(ctx context.Context, req TaskEnhancementRequest) (*TaskEnhancementResponse, error) {
	prompt := c.buildTaskEnhancementPrompt(req)

	response, err := c.makeRequest(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("failed to get Gemini AI response: %w", err)
	}

	enhancement, err := c.parseTaskEnhancement(response)
	if err != nil {
		return nil, fmt.Errorf("failed to parse Gemini AI response: %w", err)
	}

	return enhancement, nil
}

// RefineSubtasks uses Google Gemini AI to refine existing subtasks
func (c *GeminiClient) RefineSubtasks(ctx context.Context, taskName string, existingSubtasks []string, userFeedback string) ([]AIGeneratedSubtask, error) {
	prompt := c.buildSubtaskRefinementPrompt(taskName, existingSubtasks, userFeedback)

	response, err := c.makeRequest(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("failed to get Gemini AI response: %w", err)
	}

	subtasks, err := c.parseSubtaskRefinement(response)
	if err != nil {
		return nil, fmt.Errorf("failed to parse Gemini AI response: %w", err)
	}

	return subtasks, nil
}

// ImproveDescription uses Google Gemini AI to improve task description
func (c *GeminiClient) ImproveDescription(ctx context.Context, taskName string, currentDescription string, priority string, tags []string) (string, error) {
	prompt := c.buildDescriptionImprovementPrompt(taskName, currentDescription, priority, tags)

	response, err := c.makeRequest(ctx, prompt)
	if err != nil {
		return "", fmt.Errorf("failed to get Gemini AI response: %w", err)
	}

	description, err := c.parseDescriptionImprovement(response)
	if err != nil {
		return "", fmt.Errorf("failed to parse Gemini AI response: %w", err)
	}

	return description, nil
}

// makeRequest makes a request to the Google Gemini API with retry logic
func (c *GeminiClient) makeRequest(ctx context.Context, prompt string) (string, error) {
	var lastErr error

	for attempt := 0; attempt <= c.maxRetries; attempt++ {
		if attempt > 0 {
			// Add exponential backoff for retries
			delay := c.retryDelay * time.Duration(1<<uint(attempt-1))
			select {
			case <-ctx.Done():
				return "", ctx.Err()
			case <-time.After(delay):
			}
		}

		response, err := c.makeRequestAttempt(ctx, prompt)
		if err == nil {
			return response, nil
		}

		lastErr = err

		// Don't retry on certain errors
		if !c.shouldRetry(err) {
			break
		}
	}

	return "", fmt.Errorf("failed after %d attempts: %w", c.maxRetries+1, lastErr)
}

// makeRequestAttempt makes a single request attempt to the Google Gemini API
func (c *GeminiClient) makeRequestAttempt(ctx context.Context, prompt string) (string, error) {
	reqBody := GeminiRequest{
		Contents: []GeminiContent{
			{
				Parts: []GeminiPart{
					{
						Text: prompt,
					},
				},
				Role: "user",
			},
		},
		GenerationConfig: GeminiGenerationConfig{
			Temperature:     0.2,
			TopK:            40,
			TopP:            0.8,
			MaxOutputTokens: 2048,
		},
		SafetySettings: []GeminiSafetySettings{
			{
				Category:  "HARM_CATEGORY_HARASSMENT",
				Threshold: "BLOCK_MEDIUM_AND_ABOVE",
			},
			{
				Category:  "HARM_CATEGORY_HATE_SPEECH",
				Threshold: "BLOCK_MEDIUM_AND_ABOVE",
			},
			{
				Category:  "HARM_CATEGORY_SEXUALLY_EXPLICIT",
				Threshold: "BLOCK_MEDIUM_AND_ABOVE",
			},
			{
				Category:  "HARM_CATEGORY_DANGEROUS_CONTENT",
				Threshold: "BLOCK_MEDIUM_AND_ABOVE",
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("failed to marshal request: %w", err)
	}

	url := fmt.Sprintf("%s/models/%s:generateContent?key=%s", c.baseURL, c.model, c.apiKey)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to make request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		var errorBody bytes.Buffer
		errorBody.ReadFrom(resp.Body)
		return "", fmt.Errorf("Gemini API request failed with status %d: %s", resp.StatusCode, errorBody.String())
	}

	var response GeminiResponse
	if err := json.NewDecoder(resp.Body).Decode(&response); err != nil {
		return "", fmt.Errorf("failed to decode response: %w", err)
	}

	if len(response.Candidates) == 0 {
		return "", fmt.Errorf("no response candidates received from Gemini")
	}

	if len(response.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("no content parts received from Gemini")
	}

	return response.Candidates[0].Content.Parts[0].Text, nil
}

// buildTaskEnhancementPrompt builds an optimized prompt for task enhancement using Gemini
func (c *GeminiClient) buildTaskEnhancementPrompt(req TaskEnhancementRequest) string {
	var prompt strings.Builder

	prompt.WriteString("You are an expert AI task management assistant. Your role is to analyze tasks and provide comprehensive, actionable enhancement suggestions.\n\n")
	prompt.WriteString("**TASK TO ANALYZE:**\n")
	prompt.WriteString(fmt.Sprintf("Name: %s\n", req.TaskName))

	if req.TaskDescription != "" {
		prompt.WriteString(fmt.Sprintf("Current Description: %s\n", req.TaskDescription))
	}

	if req.ProjectContext != "" {
		prompt.WriteString(fmt.Sprintf("Project Context: %s\n", req.ProjectContext))
	}

	if req.UserPreferences != "" {
		prompt.WriteString(fmt.Sprintf("User Preferences: %s\n", req.UserPreferences))
	}

	prompt.WriteString("\n**INSTRUCTIONS:**\n")
	prompt.WriteString("Analyze this task and provide a comprehensive enhancement. Focus on breaking down complex work into manageable, actionable steps.\n\n")

	prompt.WriteString("**REQUIRED JSON RESPONSE FORMAT:**\n")
	prompt.WriteString("{\n")
	prompt.WriteString("  \"enhanced_description\": \"A clear, detailed description of what needs to be done (2-3 sentences)\",\n")
	prompt.WriteString("  \"emoji\": \"One appropriate emoji that represents this task\",\n")
	prompt.WriteString("  \"subtasks\": [\n")
	prompt.WriteString("    {\n")
	prompt.WriteString("      \"name\": \"Clear, actionable subtask name\",\n")
	prompt.WriteString("      \"description\": \"Brief but specific description\",\n")
	prompt.WriteString("      \"estimated_duration_minutes\": 30,\n")
	prompt.WriteString("      \"order\": 1\n")
	prompt.WriteString("    }\n")
	prompt.WriteString("  ],\n")
	prompt.WriteString("  \"category\": \"One of: Work, Personal, Bug, Feature, Research, Meeting, Planning, Design, Development, Testing, Documentation\",\n")
	prompt.WriteString("  \"priority\": \"One of: Low, Medium, High\",\n")
	prompt.WriteString("  \"estimated_duration_minutes\": 120,\n")
	prompt.WriteString("  \"tags\": [\"relevant\", \"specific\", \"tags\"]\n")
	prompt.WriteString("}\n\n")

	prompt.WriteString("**GUIDELINES:**\n")
	prompt.WriteString("- Break complex tasks into 3-7 logical, sequential subtasks\n")
	prompt.WriteString("- Provide realistic time estimates based on task complexity\n")
	prompt.WriteString("- Use professional, clear, and actionable language\n")
	prompt.WriteString("- Ensure subtasks follow a logical workflow order\n")
	prompt.WriteString("- Include relevant tags that help with categorization and search\n")
	prompt.WriteString("- Focus on deliverable outcomes, not just activities\n")
	prompt.WriteString("- Consider dependencies between subtasks\n\n")

	prompt.WriteString("**OUTPUT REQUIREMENTS:**\n")
	prompt.WriteString("- Return ONLY the valid JSON response\n")
	prompt.WriteString("- Do not include any markdown formatting, explanations, or additional text\n")
	prompt.WriteString("- Ensure all JSON is properly formatted and escaped")

	return prompt.String()
}

// buildSubtaskRefinementPrompt builds an optimized prompt for subtask refinement
func (c *GeminiClient) buildSubtaskRefinementPrompt(taskName string, existingSubtasks []string, userFeedback string) string {
	var prompt strings.Builder

	prompt.WriteString("You are an expert task management assistant. Refine and improve the following subtasks based on user feedback.\n\n")
	prompt.WriteString(fmt.Sprintf("**TASK:** %s\n\n", taskName))
	prompt.WriteString("**CURRENT SUBTASKS:**\n")

	for i, subtask := range existingSubtasks {
		prompt.WriteString(fmt.Sprintf("%d. %s\n", i+1, subtask))
	}

	if userFeedback != "" {
		prompt.WriteString(fmt.Sprintf("\n**USER FEEDBACK:** %s\n", userFeedback))
	}

	prompt.WriteString("\n**INSTRUCTIONS:**\n")
	prompt.WriteString("Improve the subtasks by addressing the user feedback. Make them more actionable, clearer, or better organized as requested.\n\n")

	prompt.WriteString("**REQUIRED JSON RESPONSE FORMAT:**\n")
	prompt.WriteString("{\n")
	prompt.WriteString("  \"subtasks\": [\n")
	prompt.WriteString("    {\n")
	prompt.WriteString("      \"name\": \"Improved, clear subtask name\",\n")
	prompt.WriteString("      \"description\": \"Brief but specific description\",\n")
	prompt.WriteString("      \"estimated_duration_minutes\": 30,\n")
	prompt.WriteString("      \"order\": 1\n")
	prompt.WriteString("    }\n")
	prompt.WriteString("  ]\n")
	prompt.WriteString("}\n\n")

	prompt.WriteString("**GUIDELINES:**\n")
	prompt.WriteString("- Address the specific feedback provided by the user\n")
	prompt.WriteString("- Maintain logical workflow order\n")
	prompt.WriteString("- Use clear, actionable language\n")
	prompt.WriteString("- Provide realistic time estimates\n")
	prompt.WriteString("- Ensure subtasks are specific and measurable\n\n")

	prompt.WriteString("**OUTPUT REQUIREMENTS:**\n")
	prompt.WriteString("- Return ONLY the valid JSON response\n")
	prompt.WriteString("- Do not include any markdown formatting or additional text")

	return prompt.String()
}

// buildDescriptionImprovementPrompt builds an optimized prompt for description improvement
func (c *GeminiClient) buildDescriptionImprovementPromptOld(taskName, currentDescription, context string) string {
	prompt := fmt.Sprintf(`You are an expert technical writer and task management specialist. Improve the following task description to be more clear, actionable, and comprehensive.

**TASK NAME:** %s

**CURRENT DESCRIPTION:** %s`, taskName, currentDescription)

	if context != "" {
		prompt += fmt.Sprintf(`

**ADDITIONAL CONTEXT:** %s`, context)
	}

	prompt += `

**INSTRUCTIONS:**
Rewrite the task description to be:
- Clear and specific about what needs to be accomplished
- Actionable with concrete deliverables
- Professional and well-structured
- Comprehensive but concise (2-4 sentences)
- Focused on outcomes rather than just activities

**OUTPUT REQUIREMENTS:**
- Provide ONLY the improved description as plain text
- Do not include any JSON formatting, quotes, or additional explanations
- Do not add prefixes like "Here's the improved description:" or similar
- Make it ready to use directly as a task description`

	return prompt
}

// parseTaskEnhancement parses the Gemini AI response for task enhancement
func (c *GeminiClient) parseTaskEnhancement(response string) (*TaskEnhancementResponse, error) {
	// Clean the response and extract JSON
	cleanResponse := strings.TrimSpace(response)

	// Remove markdown code blocks if present
	if strings.HasPrefix(cleanResponse, "```json") {
		cleanResponse = strings.TrimPrefix(cleanResponse, "```json")
		cleanResponse = strings.TrimSuffix(cleanResponse, "```")
	} else if strings.HasPrefix(cleanResponse, "```") {
		cleanResponse = strings.TrimPrefix(cleanResponse, "```")
		cleanResponse = strings.TrimSuffix(cleanResponse, "```")
	}

	cleanResponse = strings.TrimSpace(cleanResponse)

	// Find JSON boundaries
	jsonStart := strings.Index(cleanResponse, "{")
	jsonEnd := strings.LastIndex(cleanResponse, "}")

	if jsonStart == -1 || jsonEnd == -1 {
		return nil, fmt.Errorf("no valid JSON found in Gemini response: %s", response)
	}

	jsonData := cleanResponse[jsonStart : jsonEnd+1]

	var enhancement TaskEnhancementResponse
	if err := json.Unmarshal([]byte(jsonData), &enhancement); err != nil {
		return nil, fmt.Errorf("failed to parse JSON from Gemini response: %w\nResponse: %s", err, jsonData)
	}

	// Validate required fields
	if enhancement.EnhancedDescription == "" {
		return nil, fmt.Errorf("missing enhanced_description in Gemini response")
	}

	return &enhancement, nil
}

// parseSubtaskRefinement parses the Gemini AI response for subtask refinement
func (c *GeminiClient) parseSubtaskRefinement(response string) ([]AIGeneratedSubtask, error) {
	// Clean the response and extract JSON
	cleanResponse := strings.TrimSpace(response)

	// Remove markdown code blocks if present
	if strings.HasPrefix(cleanResponse, "```json") {
		cleanResponse = strings.TrimPrefix(cleanResponse, "```json")
		cleanResponse = strings.TrimSuffix(cleanResponse, "```")
	} else if strings.HasPrefix(cleanResponse, "```") {
		cleanResponse = strings.TrimPrefix(cleanResponse, "```")
		cleanResponse = strings.TrimSuffix(cleanResponse, "```")
	}

	cleanResponse = strings.TrimSpace(cleanResponse)

	// Find JSON boundaries
	jsonStart := strings.Index(cleanResponse, "{")
	jsonEnd := strings.LastIndex(cleanResponse, "}")

	if jsonStart == -1 || jsonEnd == -1 {
		return nil, fmt.Errorf("no valid JSON found in Gemini response: %s", response)
	}

	jsonData := cleanResponse[jsonStart : jsonEnd+1]

	var result struct {
		Subtasks []AIGeneratedSubtask `json:"subtasks"`
	}

	if err := json.Unmarshal([]byte(jsonData), &result); err != nil {
		return nil, fmt.Errorf("failed to parse JSON from Gemini response: %w\nResponse: %s", err, jsonData)
	}

	return result.Subtasks, nil
}

// parseDescriptionImprovement parses the Gemini AI response for description improvement
func (c *GeminiClient) parseDescriptionImprovement(response string) (string, error) {
	// For description improvement, we expect plain text response
	// Clean up any extra formatting that Gemini might add
	cleanResponse := strings.TrimSpace(response)

	// Remove quotes if the entire response is wrapped in them
	if strings.HasPrefix(cleanResponse, `"`) && strings.HasSuffix(cleanResponse, `"`) {
		cleanResponse = strings.Trim(cleanResponse, `"`)
	}

	if cleanResponse == "" {
		return "", fmt.Errorf("empty description received from Gemini")
	}

	return cleanResponse, nil
}

// shouldRetry determines if an error should trigger a retry
func (c *GeminiClient) shouldRetry(err error) bool {
	if err == nil {
		return false
	}

	errStr := err.Error()

	// Don't retry on authentication errors
	if strings.Contains(errStr, "401") || strings.Contains(errStr, "403") {
		return false
	}

	// Don't retry on invalid request errors
	if strings.Contains(errStr, "400") {
		return false
	}

	// Retry on rate limiting
	if strings.Contains(errStr, "429") {
		return true
	}

	// Retry on server errors
	if strings.Contains(errStr, "500") || strings.Contains(errStr, "502") ||
		strings.Contains(errStr, "503") || strings.Contains(errStr, "504") {
		return true
	}

	// Retry on network/timeout errors
	if strings.Contains(errStr, "timeout") || strings.Contains(errStr, "connection") {
		return true
	}

	// Don't retry by default
	return false
}

// buildDescriptionImprovementPrompt creates a prompt for improving task descriptions
func (c *GeminiClient) buildDescriptionImprovementPrompt(taskName, currentDescription, priority string, tags []string) string {
	var prompt strings.Builder

	prompt.WriteString("You are a professional task management assistant. Your job is to improve task descriptions to make them clear, actionable, and comprehensive.\n\n")

	prompt.WriteString("TASK DETAILS:\n")
	prompt.WriteString(fmt.Sprintf("- Task Name: %s\n", taskName))

	if currentDescription != "" {
		prompt.WriteString(fmt.Sprintf("- Current Description: %s\n", currentDescription))
	} else {
		prompt.WriteString("- Current Description: (empty or minimal)\n")
	}

	if priority != "" {
		prompt.WriteString(fmt.Sprintf("- Priority: %s\n", priority))
	}

	if len(tags) > 0 {
		prompt.WriteString(fmt.Sprintf("- Tags: %s\n", strings.Join(tags, ", ")))
	}

	prompt.WriteString("\nPLEASE PROVIDE:\n")
	prompt.WriteString("An improved, professional task description that:\n")
	prompt.WriteString("1. Clearly explains what needs to be accomplished\n")
	prompt.WriteString("2. Includes specific, measurable success criteria\n")
	prompt.WriteString("3. Mentions any relevant context or constraints\n")
	prompt.WriteString("4. Uses professional, clear language\n")
	prompt.WriteString("5. Is concise but comprehensive (2-4 sentences)\n")
	prompt.WriteString("6. Focuses on the 'what' and 'why', not the 'how'\n\n")

	prompt.WriteString("IMPORTANT:\n")
	prompt.WriteString("- Return ONLY the improved description text\n")
	prompt.WriteString("- Do not include any explanations, headers, or formatting\n")
	prompt.WriteString("- Do not wrap the response in quotes\n")
	prompt.WriteString("- Make it actionable and professional\n\n")

	prompt.WriteString("Improved Description:")

	return prompt.String()
}
